version: "3.8"
services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - ./db/data:/var/lib/postgresql/data
        ports:
            - ${DB_PORT}:5432