services:
  db:
    container_name: postgres_db
    build: ./postgres
    restart: always
    image: postgres:latest
    env_file: 
      - ./postgres/database.env
    volumes:
      - ./postgres/volume:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      - network
  
  graphql:
    container_name: postgraphile
    build: ./postgraphile
    env_file:
      - ./postgraphile/postgraphile.env
    ports:
      - 5433:5433
    depends_on:
      - db
    networks:
      - network

networks:
  network:
    