services:
  postgres:
    container_name: postgres
    build: ./postgres
    restart: always
    image: postgres:latest
    env_file: 
      - ./postgres/database.env
    volumes:
      - ./postgres/volume:/var/lib/postgresql
    ports:
      - 5432:5432